### ISSUE TITLE
Make float32 default float type

### ISSUE THREAD

**Issue by dselivanov** [dfalbel/torch#12]
I believe it makes sense to make `kFloat` as default type for numeric values. Reasons are following:
- all calculation on GPU are single-precision optimized. Double precision arithmetics is usually 10x+ times slower
- all `<float32>` tensors consumes 2x less memory and GPU memory is expensive resource

Also may be we should follow `numpy` naming conventions for `dtype` - `float32`, `float64`, etc

**Comment by dfalbel** [comment]
I agree. I will work on this. I think this will add one copy ( https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to ) but faster computation should compensate.

Also agree with numpy naming.

**Comment by dfalbel** [comment]
Now float32 is the default numeric type. I will make sure that when we add a dtype = "float64" to `tensor` , R won't copy the tensor again.

**Comment by dfalbel** [comment]
This is done. 
I added some docs here on how our wrapper converts R objects to Tensors. https://dfalbel.github.io/torch/articles/tensors.html
