### ISSUE TITLE
tch_randn(-1) crashes my R session 

### ISSUE THREAD

**Issue by Athospd** [dfalbel/torch#20]
I tried to stress tch_randn() by passing the unexpected -1 value as the size arg and it made my R session  crash.

I don't know if we must bother with it right now, make value checks is a pain in the ass, but it is good to know that unexpected arg values might lead to a unpleasant experiences.

**Comment by dfalbel** [comment]
Yes, we need to think on a default strategy for dealing with wrong arguments. Maybe define some internal functions to validate common classes like IntLists, sizes, etc.

**Comment by dfalbel** [comment]
This is related to #27
