### ISSUE TITLE
divergence between doc and source for logsumexp function 

### ISSUE THREAD

**Issue by Athospd** [dfalbel/torch#29]
About `tch_logsumexp()`

[Doc says it accepts](https://pytorch.org/docs/stable/torch.html#torch.logsumexp) **dim** (int or tuple of python:ints) – the dimension or dimensions to reduce
[Source say it accepts](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/ReduceOps.cpp#L384) int64_t **dim**

When I tried to pass `Rcpp::Nullable<Rcpp::IntegerVector> dim` to `logsumexp` it thrown an error.
And when I passed `std::int64_t dim` it finally worked out.

Am I missing something?

**Comment by dfalbel** [comment]
This seems like a bug in pytorch itself - or in the docs. See for example:

```
>>> import torch
>>> x = torch.randn(2,2,2)
>>> torch.logsumexp(x, 0)
tensor([[1.4389, 0.9872],
        [0.9308, 1.1934]])
>>> torch.logsumexp(x, (0,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: logsumexp(): argument 'dim' (position 2) must be int, not tuple
```

I think we should mimic pytorch's behavior for now and file an issue in pytorch.
